### ISSUE TITLE
Display first task as current

### ISSUE THREAD

**Issue by A11yship** [A11yship/capstone-project#11]
# Value Proposition

**As a** user
**I want to** have marked the first task as current task
**So that** I can fulfill it

# Description

![Image](https://user-images.githubusercontent.com/107836585/185155553-fd88e972-9b52-4644-aa47-acc7f953f03a.png)

# Acceptance Criteria

- [x] First task of the list is displays bigger above the list 
- [x] The list entry is highlighted 

# Tasks

- [x] Add basic styling 
- [x] Write a test to confirm that the correct entry is displayed

# Complexity

 S

**Comment by j-eick** [comment]
> _"test if the correct entry is displayed"_

If you formulate this as a task you should also make it an AC.
➡️ "A successful test confirms that the correct entry is displayed"

### Task
➡️ "Write a test to confirm the correct entry"

**Comment by niklashmbgr** [comment]
looks good now 👍
