### ISSUE TITLE
Mark task as done

### ISSUE THREAD

**Issue by A11yship** [A11yship/capstone-project#12]
# Value Proposition

**As a** user
**I want to** mark a task as done
**So that** it is now longer shown

# Description

![Image](https://user-images.githubusercontent.com/107836585/185390713-3e57c43d-2d9e-448c-b9a3-614b69261cc7.png)

# Acceptance Criteria

- [x] Clicking the button marks the second list entry as current task
- [x] Clicking the button deletes the first list entry
- [x] Display "Keine Aufgaben" if the task list is empty

# Tasks

- [x] create button component with basic styling
- [x] Test Button component
- [ ] ~~Test that task is no longer displayed~~
- [ ] ~~Test that there is a new current task or the list is empty~~

# Complexity

 M
