### ISSUE TITLE
Add form page

### ISSUE THREAD

**Issue by A11yship** [A11yship/capstone-project#14]
# Value Proposition

**As a** user
**I want to** have an extra page for the form
**So that** the index page is more clear and the form page as well

# Description

![Image](https://user-images.githubusercontent.com/107836585/185623208-f6229a60-73c2-4702-9d88-624e3061a3d0.png)

# Acceptance Criteria

- [ ] Have a fixed navbar
- [ ] clicking the navbar items redirects the user to the page
- [ ] After clicking the submit button the user is redirected to the main page

# Tasks

- [ ] Create nav bar component
- [ ] Add routing between the pages
- [ ] Test if nav bar is displayed

# Complexity

S
