### ISSUE TITLE
Select list of current tasks

### ISSUE THREAD

**Issue by A11yship** [A11yship/capstone-project#15]
# Value Proposition

**As a** user
**I want to** select the tasks, I want to do next
**So that** I only see them and won't be overwhelmed by all the tasks

# Description

![Image](https://user-images.githubusercontent.com/107836585/185885465-143e3a05-7d07-4f3c-85a6-89e76fdd1471.png)

# Acceptance Criteria

- [x] New section for the current tasks is displayed
- [x] Clicking on the "Neue Liste" opens a form
- [x] In the Form tasks can be selected
- [x] Submitting the form, close it an the selected list is displayed
- [x] The "Neue Liste" button switch to edit list
- [x] the current task field gets its information from the new list an operates on the first entry of the new list
- [x] Display "Keine aktuellen Aufgaben" in current task field, if the list is empty

# Tasks

- [x] use button component
- [x] write a form component ~~with test~~
- [x] update current task field
- [x] update done button
- [ ] ~~test if the new list is displayed~~

# Complexity

L
