### ISSUE TITLE
edit task

### ISSUE THREAD

**Issue by A11yship** [A11yship/capstone-project#20]
# Value Proposition

**As a** user
**I want to** edit a task
**So that** I can change the name and/or duration

# Description

![Image](https://user-images.githubusercontent.com/107836585/186680238-42b9db5d-9798-477f-967f-d3b1266f1adb.png)

# Acceptance Criteria

- [x] Clicking on the edit button redirects to the form page
- [x] The inputs are filled with the task information 
- [x] Saving the task redirects to the list
- [x] A cancel Button is displayed. Clicking it redirects to the list without changing the task

# Tasks

- [x] Add edit button
- [x] Add cancel button to the form
- [x] add new function to use store

# Complexity

S
