### ISSUE TITLE
delete task

### ISSUE THREAD

**Issue by A11yship** [A11yship/capstone-project#22]
# Value Proposition

**As a** user
**I want to** delete a task
**So that** it is no longer stored in the app.

# Description

![Image](https://user-images.githubusercontent.com/107836585/186690250-d560b1d1-e161-4662-acd6-3de0dc872945.png)

# Acceptance Criteria

- [x] Clicking the delete button display a confirmation field 
- [x] Cancel the delete closes the confirmation field
- [x] Submitting the delete, deletes the task from the data and close the confirmation

# Tasks

- [x] write component for confirmation field
- [x] write delete function in useStore
- [ ] ~~test if the confirmation field is displayed~~

# Complexity

 S
