### ISSUE TITLE
Generate Current List

### ISSUE THREAD

**Issue by A11yship** [A11yship/capstone-project#23]
# Value Proposition

**As a** user
**I want to** auto generate a list of current task
**So that** I don't have ti think about the next tasks

# Description

On the MainPage is a button "Liste generieren" next to the "Neue Liste" button, clicking it opens the following Form:

![Image](https://user-images.githubusercontent.com/107836585/187160639-daa4b790-d1fd-44b2-af56-3b3c88e641ff.png)

the form has a cancel button as well

# Acceptance Criteria

- [x] Clicking button "Liste generieren" opens the form
- [x] submitting the form generates a list, that matches the requirements and redirects back to the main page
- [x] clicking the cancel button redirects to the main page without a new list

# Tasks

- [x] writing a new form component
- [x] writing logic for generating a list
- [ ] ~~Testing if the form is displayed~~

# Complexity

M-L

**Comment by niklashmbgr** [comment]
nice userstory 👍
