### ISSUE TITLE
Add page for list

### ISSUE THREAD

**Issue by A11yship** [A11yship/capstone-project#24]
# Value Proposition

**As a** user
**I want to** have an extra page for the list of all tasks
**So that** the index page is more clear

# Description

![Image](https://user-images.githubusercontent.com/107836585/187470181-a9b52f05-9039-4c74-894c-60ad36191d0b.png)

# Acceptance Criteria

- [x] Have a third button in the navigation
- [x] display the list on the new page

# Tasks

- [x] add new Page

# Complexity

XS
