### ISSUE TITLE
Styling

### ISSUE THREAD

**Issue by A11yship** [A11yship/capstone-project#27]
# Value Proposition

**As a** user
**I want to**have a nice looking app
**So that** I like to use it and it is simple

# Acceptance Criteria

- [x] Add color scheme: https://coolors.co/f9f2dd-ddaaff-9900ff-5b2281-1a1a34
- [x] Use Icons in the navigation

# Tasks

- [x] Add components
- [x] Add Feedback (aka hover current, etc.)
- [x] Add formatting
- [x] maybe change font
- [x] add consistent alignment

# Complexity

XL
