### ISSUE TITLE
Add Task

### ISSUE THREAD

**Issue by A11yship** [A11yship/capstone-project#3]
# Value Proposition

**As a** user
**I want to** add a new task
**So that** the task is saved and I can complete them later

# Description
![AddTask](https://user-images.githubusercontent.com/107836585/184323255-fd4a0289-2f12-4634-95ad-5280cc517bcd.png)

# Acceptance Criteria

- [x] An input field for the task's name is displayed (label: "Aufgabe")
- [x] An input field for the task's duration is displayed (label: "Dauer")
- [x] A submit button is displayed
- [x] All two fields are required
- [x] The duration is a number (time works other than I thought)
- [x] After submitting the new task is displayed 

# Tasks

- [x] Create a form component with two input fields and a submit button
- [x] Add `event.preventDefault()` to the form submit
- [x] Create form validation
- [x] Write tests to check the form validation
- [x] Add state handling (with zustand.js)
- [x] Add basic styles

# Complexity

L

**Comment by RobertBReich** [comment]
Hi Hannah,

looks cool. Tiny typo @"All two fields a required" -> are 😄

cheers
R.

**Comment by RobertBReich** [comment]
👍

**Comment by ahohnsen** [comment]
Hey Hannah,

Well done! 
Just keep in mind that you do not need to describe the things which are already in your scribble 🙂
