### ISSUE TITLE
Tests

### ISSUE THREAD

**Issue by A11yship** [A11yship/capstone-project#32]
# Value Proposition

**As a** developer
**I want to** write more tests
**So that** I'm sure that changing the code 

# Acceptance Criteria

- [ ] Tests the generate list form
- [ ] Update tests for the add task form
- [ ] Test if the the delete modal is displayed
- [ ] Tests if the components for the drag and drop component are displayed
- [ ] Test the don button

# Tasks

- [ ] Done button: Task not longer displayed
- [ ] Done Button: new current task is displayed or list is empty

# Complexity

 XL
