### ISSUE TITLE
Refactor Code

### ISSUE THREAD

**Issue by A11yship** [A11yship/capstone-project#33]
# Value Proposition

**As a** developer
**I want to** refactor my code
**So that** it is clearer and better to read and understand 

# Acceptance Criteria

- [ ] Clearer Code
- [ ] Add comments
- [ ] Add heads to pages

# Tasks

- [ ] restructure folder/file structure
- [ ] restructure forms
- [ ] Check if components can be reused

# Complexity

L
