### ISSUE TITLE
Signal Sound

### ISSUE THREAD

**Issue by A11yship** [A11yship/capstone-project#34]
# Value Proposition

**As a** user
**I want to** have a sound signal when a timer ends
**So that** I know the time is over without looking at the screen all the time

# Acceptance Criteria

- [ ] Hearing a sound, when the time is over

# Tasks

- [ ] find a library for sound
- [ ] install the library
- [ ] select a sound

# Complexity

M
