### ISSUE TITLE
Add timer function for current task

### ISSUE THREAD

**Issue by A11yship** [A11yship/capstone-project#4]
# Value Proposition

**As a** user
**I want to** have a timer
**So that** I can see how much time is left for the task and get an alert, when the time is over 

# Description

![Image](https://user-images.githubusercontent.com/107836585/185382974-fba90020-12e7-4683-9c4e-8aa6022e8b56.png)

# Acceptance Criteria

- [x] The (remaining) time is displayed as a countdown
- [x] The start/break button ist between the counter field and the existing done button
- [ ] Clicking the start button starts the timer and change it to break
- [ ] Clicking the break button paused the timer

# Tasks

- [x] Write a timer function, that counts down the time 
- [x] Write tests to check if the button is clickable

# Complexity

 M

**Comment by ahohnsen** [comment]
Hey Hannah,

I would not recommend to start your project with this user story. I would suggest to implement first the main functionalities like adding new tasks and mark tasks as current task & completed task. As a next step you could then implement the timer for the current task. 
Of course, you do not need to delete this user story. I suggest to keep it for later and work on above mentioned user stories first. Once you are ready to implement the timer feature you can come back to this user story and adjust it if necessary.
