### ISSUE TITLE
visualize remaining time

### ISSUE THREAD

**Issue by A11yship** [A11yship/capstone-project#5]
# Value Proposition

**As a** user
**I want to** see the remaining time on a clock
**So that** i have a better visualization and understanding how much time is left

# Description

![Image](https://user-images.githubusercontent.com/107836585/185878165-8729e5aa-89cb-4f21-8206-4026a219973e.png)
blue is the remaining time and red the total time

# Acceptance Criteria

- [x] A Clock is displayed
- [x] The total time is displayed on the clock
- [x] The remaining time is displayed
- [x] Clicking the button start/pause the timer

# Tasks

- [x] style a clock with css
- [x] create a dynamic circle segment
- [x] Periodically the remaining time is updated (Whats a good one?)
- [ ] ~~Test if the clock is displayed~~

# Complexity

 L

**Comment by PhilipZi** [comment]
Hey Hannah alles super, aber leider sieht man anhand der description nicht, wo die Zeit dargestellt werden soll? Einfach nur anhand des Bildes oder auch in digitaler/analoger form? Das ist leider nicht ganz klar, sonst alles top :)

**Comment by PhilipZi** [comment]
es geht mir um die Aussage'' The total time is displayed on the clock''
