### ISSUE TITLE
Display list of tasks

### ISSUE THREAD

**Issue by A11yship** [A11yship/capstone-project#6]
# Value Proposition

**As a** user
**I want to** see a list of tasks
**So that** I have a overview about them and know whats on my list

# Description

![TaskList](https://user-images.githubusercontent.com/107836585/184628437-9ec1399b-d847-4bcd-8b10-785482ff22b5.png)

# Acceptance Criteria

- [x] A Headline is displayed
- [x] A list of tasks is displayed
- [x] Every task has a name and a time

# Tasks

- [x] Create dummy data for 2 tasks with id, name and time
- [x] Create a list for the tasks
- [x] Add basic styling to the list items

# Complexity

 M

**Comment by RobertBReich** [comment]
Hi Hannah,

looks good. "tasks" in "i want to see" line 2, other than that: 👍

cheers
R.
