### ISSUE TITLE
select current task

### ISSUE THREAD

**Issue by A11yship** [A11yship/capstone-project#9]
# Value Proposition

**As a** user
**I want to** mark one task as current task
**So that** I can fulfill it

# Description

![Image](https://user-images.githubusercontent.com/107836585/184850745-237271f7-0269-4968-8fe9-1c33f8557f3f.png)

# Acceptance Criteria

- [ ] clicking on a tasks selects the task and displays it above the list 
- [ ] clicking on an other tasks change the selection
- [ ] clicking a second time on a task removes the selection
- [ ] Display "Keine Aufgabe ausgewählt" when no task is selected

# Tasks

- [ ] list the tasks that need to be performed within the dev team
- [ ] e.g. Components, Storybook, testing
- [ ] ...

# Complexity

XS, S, M, L, XL
